---
title: "PDX models of cetuximab response"
author: "Elana Fertig"
date: "Dec 27, 2016"
output: pdf_document
---

```{r,echo=FALSE,message=FALSE}
library('xlsx')
```

```{r,echo=FALSE}
normPlotPDX <- function(PDXName='') {
  
  PDXData <- read.xlsx('Cetuximab data Across PDX.xlsx',
                       sheetName = PDXName, startRow=2)
  ctxCol <- which(substr(colnames(PDXData),1,1)=='C')
  colnames(PDXData)[1] <- 'Days'
  colnames(PDXData)[2:(ctxCol-1)] <- paste('PBS',1:(ctxCol-2),sep=".")
  colnames(PDXData)[ctxCol:ncol(PDXData)] <- paste('CTX',1:(ncol(PDXData)-ctxCol+1),
                                                   sep='.')
  
  PDX.Norm <- sweep(PDXData[,2:ncol(PDXData)],2,
                    as.numeric(PDXData[1,2:ncol(PDXData)]),
                    FUN="/")
  meanProfile <- apply(PDX.Norm,1,tapply,substr(colnames(PDX.Norm),1,1),mean,
                     na.rm=T)
  
  matplot(PDXData$Days,PDX.Norm,type='b',
          col=ifelse(substr(colnames(PDX.Norm),1,1)=='C','blue','red'),
          lwd=0.5, xlab='Days', ylab='Tumor Volume to Tumor Volume at day 1', 
          main=PDXName, pch=sapply(strsplit(colnames(PDX.Norm),
                                            split="\\."),function(x){x[[2]]}))
  
  lines(PDXData$Days,meanProfile['C',],col='blue',lwd=2)
  lines(PDXData$Days,meanProfile['P',],col='red',lwd=2)
  legend('topleft',fill=c('red','blue'),legend=c('PBS','CTX'))
  
  return(list(PDXData=PDXData, PDXNorm=PDX.Norm))
  
}
```

```{r,echo=FALSE,fig.keep='all',message=FALSE,results='hide'}
PDXModels <- c('409 PDX F2','428 PDX F3','465 PDX F3',
               '425 PDX F4','425 PDX F6')
PDXInitPBS <- PDXFinalPBS <- PDXInitCTX <- PDXFinalCTX <- list()
for (PDX in PDXModels) {
  message(PDX)
  PDXDat <- normPlotPDX(PDX)
  PDXInitPBS[[PDX]] <- 
    PDXDat$PDXData[1,grep('PBS',colnames(PDXDat$PDXData))]
  PDXInitCTX[[PDX]] <- 
    PDXDat$PDXData[1,grep('CTX',colnames(PDXDat$PDXData))]
}
```

